# List of Yaml data

yamlFiles:
  teas:
    name: teas
    fields:
      - ideogram
      - pinyin
      - type
      - families
      - harvests
      - provinces
      - towns
      - cultivars
      - pickings
      - elevations
      - oxidations
      - fermentation
      - brews
  type:
    name: type
  families:
    name: families
  harvest:
    name: harvests
  cultivars:
    name: cultivars
  provinces:
    name: provinces
  towns:
    name: towns
  picking:
    name: pickings
  brewing-types:
    name: brews
  themes:
    name: themes

themes:
  - brews
  - families
  - pickings
  - towns
  - cultivars
  - harvests
  - provinces
  - teas
  - type
